version: "3.8"

services:
#  app:
#    image: 'app:v1'
#    container_name: springboot_app
#    hostname: springboot_app
#    env_file: .env
#    ports:
#      - '8081:8080'
#    environment:
#      - TZ=Asia/Ho_Chi_Minh
#      - DBMS_CONNECTION=${DBMS_CONNECTION}
#      - KAFKA_SERVER=kafka:9094
#      - API_SECRET_CLOUDINARY=${API_SECRET_CLOUDINARY}
#      - SECRET_KEY_VNPAY=${SECRET_KEY_VNPAY}
#      - TOKEN_GHN=${TOKEN_GHN}
#      - API_KEY_BREVO=${API_KEY_BREVO}
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /etc/timezone:/etc/timezone:ro
#    networks:
#      - default-network
  kafka:
    image: 'bitnami/kafka:3.8'
    container_name: kafka
    hostname: kafka
    env_file: .env
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=${KAFKA_CFG_CONTROLLER_QUORUM_VOTERS}
      - KAFKA_CFG_LISTENERS=${KAFKA_CFG_LISTENERS}
      - KAFKA_CFG_ADVERTISED_LISTENERS=${KAFKA_CFG_ADVERTISED_LISTENERS}
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - default-network
  redis:
    image: 'redis:latest'
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'
    networks:
      - default-network
networks:
  default-network:
    driver: bridge