version: "3.8"

services:
#  app:
#    image: 'app:v1'
#    container_name: app
#    hostname: app
#    restart: on-failure
#    ports:
#      - '8081:8080'
#    environment:
#      - TZ=Asia/Ho_Chi_Minh
#      - DBMS_CONNECTION=${DBMS_CONNECTION}
#      - ELASTICSEARCH_URIS=http://elasticsearch:9200
#      - KAFKA_SERVER=kafka:9094
#      - API_SECRET_CLOUDINARY=${API_SECRET_CLOUDINARY}
#      - CLIENT_SECRET_GOOGLE=${CLIENT_SECRET_GOOGLE}
#      - SECRET_KEY_VNPAY=${SECRET_KEY_VNPAY}
#      - TOKEN_GHN=${TOKEN_GHN}
#      - API_KEY_BREVO=${API_KEY_BREVO}
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /etc/timezone:/etc/timezone:ro
#    networks:
#      - default-network
  kafka:
    image: 'bitnami/kafka:3.8'
    container_name: kafka
    hostname: kafka
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - default-network
  redis:
    image: 'redis:latest'
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'
    networks:
      - default-network
  elasticsearch:
    image: 'elasticsearch:8.15.5'
    container_name: elasticsearch
    hostname: elasticsearch
    ports:
      - '9200:9200'
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - default-network
  kibana:
    image: 'kibana:8.15.5'
    container_name: kibana
    hostname: kibana
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - default-network
networks:
  default-network:
    driver: bridge