version: "3.8"

services:
  app:
    build: .
    container_name: green-shop
    hostname: green-shop
    env_file: .env
    restart: always
    ports:
      - '8080:8080'
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - DBMS_CONNECTION=${DBMS_CONNECTION}
      - KAFKA_SERVER=kafka:9094
      - dock=${API_SECRET_CLOUDINARY}
      - SECRET_KEY_VNPAY=${SECRET_KEY_VNPAY}
      - TOKEN_GHN=${TOKEN_GHN}
      - API_KEY_BREVO=${API_KEY_BREVO}
      - REDIS_HOST = ${REDIS_HOST}
      - KAFKA_SERVER = ${KAFKA_SERVER}
    depends_on:
      - mysql
      - redis
      - kafka
    networks:
      - default-network

  kafka:
    image: 'bitnami/kafka:3.8'
    container_name: kafka
    hostname: kafka
    env_file: .env
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=${KAFKA_CFG_CONTROLLER_QUORUM_VOTERS}
      - KAFKA_CFG_LISTENERS=${KAFKA_CFG_LISTENERS}
      - KAFKA_CFG_ADVERTISED_LISTENERS=${KAFKA_CFG_ADVERTISED_LISTENERS}
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - default-network

  redis:
    image: 'redis:latest'
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'
    networks:
      - default-network

  mysql:
    image: mysql:8.0-debian
    container_name: mysql
    env_file: .env
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    networks:
      - default-network

volumes:
  mysql_data:
    name: mysql_data
    driver: local

networks:
  default-network:
    driver: bridge