server:
  port: 8080

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/green-shop}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:mysql}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  elasticsearch:
    uris: http://localhost:9200
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"

jwt:
  signerKey: 1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij
  duration: 1 #hour

cloudinary:
  cloud_name: drgidfvnd
  api_key: 195446941243745
  api_secret: ${API_SECRET_CLOUDINARY}

outbound:
  identity:
    client-id: 726980649628-lp3bilg5elg8bma1cpqkgi6jbimgc40r.apps.googleusercontent.com
    client-secret: ${CLIENT_SECRET_GOOGLE}
    redirect-uri: http://localhost:3000/authenticate
    grant-type: authorization_code

resource:
  defaultImage: https://res.cloudinary.com/drgidfvnd/image/upload/v1735303638/no-image.webp

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs.html

open:
  api:
    title: API Documents
    version: v1.0.0
    description: APIs docs for Green Shop website
    serverUrl: ${API_SERVER_URL:http://localhost:8080}
    serverDescription: local

payment:
  vnpay:
    pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: ${PAYMENT_RETURN_URL:http://localhost:8080/payment/vn-pay-callback}
    tmn-code: 1BPJTK72
    secret-key: ${SECRET_KEY_VNPAY}
    version: 2.1.0
    command: pay
    order-type: other

ghn:
  token: ${TOKEN_GHN}
  shop-id: 5512864

brevo:
  api-key: ${API_KEY_BREVO}
  template-id: 1