server:
  port: 8080

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/green-shop}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:mysql}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: 1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij
  duration: 1 #hour

cloudinary:
  cloud_name: dcw5wq1ka
  api_key: 228462159873377
  api_secret: VOz0qy1Fh1TwwdqF5ZXjpytRVjY

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs.html

open:
  api:
    title: API Documents
    version: v1.0.0
    description: APIs docs for Green Shop website
    serverUrl: http://localhost:8080/
    serverDescription: local
