server:
  port: 8080

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/green-shop}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:mysql}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

jwt:
  signerKey: 1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij
  duration: 1 #hour

cloudinary:
  cloud_name: drgidfvnd
  api_key: 195446941243745
  api_secret: 4RQj5g79A55YCQeybvBxXBTTIq8

outbound:
  identity:
    client-id: 726980649628-lp3bilg5elg8bma1cpqkgi6jbimgc40r.apps.googleusercontent.com
    client-secret: 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
    redirect-uri: http://localhost:3000/authenticate
    grant-type: authorization_code

resource:
  defaultImage: https://res.cloudinary.com/drgidfvnd/image/upload/v1712980751/samples/default-image.png

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs.html

open:
  api:
    title: API Documents
    version: v1.0.0
    description: APIs docs for Green Shop website
    serverUrl: ${API_SERVER_URL:http://localhost:8080}
    serverDescription: local

payment:
  vnpay:
    pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: ${PAYMENT_RETURN_URL:http://localhost:8080/payment/vn-pay-callback}
    tmn-code: 1BPJTK72
    secret-key: WBKCQ8ZMK4WYHLH96QQCTU33ZTQLING7
    version: 2.1.0
    command: pay
    order-type: other

ghn:
  token: eb76026d-b64c-11ef-81b6-5e2e958f07fa
  shop-id: 5512864
