server:
  port: 8080

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/green-shop}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:mysql}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
