server:
  port: 8080

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/green-shop}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:mysql}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: 1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij
  duration: 1 #hour

cloudinary:
  cloud_name: drgidfvnd
  api_key: 195446941243745
  api_secret: 4RQj5g79A55YCQeybvBxXBTTIq8

resource:
  defaultImage: https://res.cloudinary.com/drgidfvnd/image/upload/v1712980751/samples/default-image.png

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs.html

open:
  api:
    title: API Documents
    version: v1.0.0
    description: APIs docs for Green Shop website
    serverUrl: http://localhost:8080/
    serverDescription: local
