name: Build Backend Project and containerize to Docker Hub
  
on:
  push:
    branches:
      - dev
    paths:
      - backend/**
      - .github/workflows/*-backend.yml

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Backend
    steps:
      - name: Checkout Backend 
        uses: actions/checkout@v4
        with:
         fetch-depth: 0
        
      - name: Setup JDK Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: 21
          cache: 'maven'
          
      - name: Build with Maven
        working-directory: ./backend
        run: mvn clean install -DskipTests
        
      - name: Login to Docker Hub Container Registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set tag for Docker image
        id: set-tag
        run: |
           SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
           TAG="version_${SHORT_SHA}"
           echo "TAG=$TAG" >> $GITHUB_OUTPUT
        
      - name: Build Docker Image with Docker CLI
        working-directory: ./backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/green-shop:${{ steps.set-tag.outputs.TAG }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/green-shop:${{ steps.set-tag.outputs.TAG }}
